idf_component_register(
    SRCS
        "app_main.c"
        "wifi_net.c"
        "nvs_config.c"
        "heap_log.c"
        "cert_gen.c"
        "config_http.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_http_server
        dns_server
        mbedtls
        umurmur
)
